### ISSUE TITLE
Error in solve.default(object$fit$hessian) :

### ISSUE THREAD

**Issue by uyghbo** [DoseResponse/drc#19]
Dear authors:
     I‘m using drc package to determine the Estimated LD50, but I've encountered several errors that I cannot figure out. Would please give me some advice? The drc package is an excellent package, however I'm still new to it.

When I ran ED(KP.LL.2, 50, interval = "delta"), It returned “Error in solve.default(object$fit$hessian) :”

I have attached my test file ("inline-supplementary-material-2.xlsx"), I think it should use the code that you describe in "four typesof selenium".

here is my code:

library(openxlsx)
KP <- read.xlsx('inline-supplementary-material-2.xlsx',
                startRow=2)
KP <- KP[,-2]
colnames(KP) <- c("type", "conc", "total", "dead")
KP.LL.2 <- drm(dead/total ~ conc, type, weights = total,data = KP,
                       fct = LL.2(), type = "binomial")
ED(KP.LL.2, 50, interval = "delta")

**Comment by uyghbo** [comment]
Supplementary Table 2. Mouse Survival in a Tail-Vein   Model of Bacteremia for Isolates Included in this Studya,b
--
Strain | Date | Dose (log10 CFU) | Total Mice | Mortalities
PABL001 | 2010/11/2 | 6.38 | 5 | 0
PABL001 | 2010/2/8 | 6.70 | 5 | 3
PABL002 | 2010/11/2 | 6.31 | 5 | 0
PABL002 | 2016/3/29 | 6.40 | 5 | 5
PABL002 | 2010/2/8 | 6.48 | 5 | 5
PABL002 | 2016/3/8 | 6.85 | 5 | 5
PABL003 | 2011/8/15 | 6.11 | 5 | 1
PABL003 | 2011/8/8 | 6.60 | 5 | 3
PABL004 | 2010/2/8 | 5.84 | 5 | 0
PABL004 | 2010/9/14 | 7.22 | 5 | 0
PABL004 | 2012/4/10 | 7.76 | 5 | 5
PABL004 | 2012/2/20 | 8.11 | 5 | 5
PABL006 | 2011/8/8 | 5.95 | 5 | 0
PABL006 | 2011/12/12 | 6.39 | 5 | 2
PABL006 | 2011/7/19 | 6.60 | 5 | 3
PABL007 | 2010/9/13 | 6.44 | 5 | 2
PABL007 | 2010/2/22 | 6.99 | 5 | 5
PABL009 | 2011/8/8 | 6.94 | 5 | 0
PABL009 | 2011/8/15 | 7.31 | 5 | 4
PABL010 | 2011/8/8 | 6.76 | 5 | 0
PABL010 | 2011/8/15 | 7.09 | 5 | 0
PABL010 | 2012/2/14 | 7.79 | 5 | 5
PABL011 | 2011/8/8 | 6.69 | 5 | 1
PABL011 | 2011/8/15 | 7.13 | 5 | 2
PABL011 | 2012/2/27 | 7.79 | 5 | 5
PABL012 | 2013/2/18 | 5.76 | 5 | 2
PABL012 | 2013/2/18 | 6.19 | 5 | 4
PABL012 | 2013/6/13 | 6.48 | 5 | 5
PABL012 | 2010/9/13 | 6.51 | 5 | 5
PABL012 | 2010/8/30 | 6.52 | 5 | 5
PABL012 | 2013/2/18 | 6.56 | 5 | 5
PABL012 | 2013/2/5 | 6.75 | 5 | 5
PABL012 | 2013/4/30 | 6.86 | 5 | 5
PABL012 | 2010/2/1 | 7.16 | 5 | 5
PABL013 | 2017/12/4 | 6.10 | 5 | 3
PABL013 | 2017/12/11 | 6.21 | 5 | 2
PABL013 | 2011/7/24 | 6.35 | 5 | 1
PABL013 | 2017/10/24 | 6.38 | 5 | 2
PABL013 | 2017/12/4 | 6.40 | 5 | 5
PABL013 | 2017/11/7 | 6.53 | 5 | 5
PABL013 | 2011/7/19 | 6.69 | 5 | 3
PABL013 | 2013/2/5 | 6.87 | 5 | 5
PABL013 | 2013/2/5 | 6.87 | 5 | 5
PABL014 | 2011/8/8 | 7.11 | 5 | 0
PABL014 | 2011/7/24 | 7.44 | 5 | 5
PABL015 | 2011/7/19 | 6.82 | 5 | 0
PABL015 | 2011/7/24 | 7.48 | 5 | 4
PABL016 | 2013/2/18 | 6.27 | 5 | 2
PABL016 | 2010/11/2 | 6.31 | 5 | 3
PABL016 | 2014/3/31 | 6.45 | 5 | 4
PABL016 | 2014/3/18 | 6.57 | 5 | 4
PABL016 | 2013/9/24 | 6.60 | 5 | 4
PABL016 | 2014/3/6 | 6.60 | 5 | 5
PABL016 | 2013/7/27 | 6.68 | 5 | 5
PABL016 | 2013/3/5 | 6.70 | 5 | 5
PABL016 | 2013/6/25 | 6.71 | 5 | 5
PABL016 | 2013/2/18 | 6.78 | 5 | 5
PABL016 | 2013/5/29 | 6.82 | 5 | 5
PABL016 | 2013/7/23 | 6.90 | 5 | 5
PABL016 | 2013/7/15 | 7.12 | 5 | 5
PABL016 | 2013/2/5 | 7.16 | 5 | 5
PABL016 | 2014/3/13 | 7.28 | 5 | 5
PABL017 | 2011/7/24 | 6.50 | 5 | 1
PABL017 | 2011/7/19 | 6.87 | 5 | 3
PABL018 | 2011/10/24 | 6.83 | 5 | 0
PABL018 | 2011/10/17 | 7.46 | 5 | 5
PABL018 | 2011/10/10 | 7.54 | 5 | 5
PABL020 | 2011/8/8 | 6.87 | 5 | 0
PABL020 | 2011/8/15 | 7.14 | 5 | 0
PABL020 | 2012/2/20 | 7.94 | 5 | 5
PABL021 | 2011/8/15 | 7.05 | 5 | 0
PABL021 | 2012/4/17 | 7.84 | 5 | 5
PABL021 | 2012/3/20 | 8.23 | 5 | 5
PABL022 | 2010/11/1 | 6.25 | 5 | 0
PABL022 | 2010/2/1 | 6.63 | 4 | 2
PABL023 | 2011/8/15 | 6.49 | 5 | 0
PABL023 | 2011/8/8 | 6.63 | 5 | 3
PABL023 | 2011/12/12 | 7.27 | 5 | 5
PABL023 | 2012/2/14 | 7.71 | 5 | 5
PABL024 | 2011/8/8 | 6.46 | 5 | 1
PABL024 | 2011/7/24 | 6.73 | 5 | 5
PABL024 | 2011/7/19 | 7.07 | 4 | 4
PABL026 | 2010/9/13 | 6.52 | 5 | 1
PABL026 | 2010/2/22 | 6.93 | 5 | 5
PABL027 | 2011/8/23 | 6.70 | 5 | 0
PABL027 | 2011/9/13 | 7.13 | 5 | 0
PABL027 | 2012/2/14 | 7.80 | 5 | 0
PABL027 | 2017/12/11 | 7.88 | 4 | 0
PABL027 | 2012/5/23 | 8.25 | 5 | 1
PABL027 | 2017/12/11 | 8.40 | 4 | 4
PABL027 | 2012/5/30 | 8.79 | 5 | 5
PABL028 | 2011/8/23 | 6.61 | 5 | 0
PABL028 | 2011/8/29 | 7.32 | 5 | 0
PABL028 | 2012/2/14 | 7.73 | 5 | 5
PABL029 | 2011/8/15 | 6.30 | 5 | 0
PABL029 | 2011/8/8 | 6.88 | 5 | 5
PABL030 | 2010/9/27 | 6.22 | 5 | 0
PABL030 | 2010/2/22 | 6.29 | 5 | 1
PABL030 | 2010/9/14 | 7.24 | 5 | 4
PABL031 | 2010/2/22 | 6.46 | 5 | 1
PABL031 | 2010/9/14 | 7.25 | 5 | 5
PABL032 | 2010/2/26 | 6.39 | 5 | 0
PABL032 | 2013/7/30 | 6.50 | 5 | 0
PABL032 | 2014/8/12 | 6.72 | 5 | 3
PABL032 | 2010/9/14 | 7.15 | 5 | 5
PABL032 | 2013/7/27 | 7.44 | 5 | 5
PABL034 | 2011/9/13 | 6.31 | 5 | 0
PABL034 | 2011/8/29 | 6.81 | 5 | 4
PABL035 | 2011/8/8 | 6.70 | 5 | 0
PABL035 | 2011/8/15 | 7.21 | 5 | 5
PABL035 | 2012/2/21 | 7.76 | 5 | 5
PABL036 | 2010/2/26 | 6.69 | 5 | 0
PABL036 | 2010/9/21 | 7.32 | 5 | 5
PABL037 | 2011/8/8 | 6.36 | 5 | 0
PABL037 | 2011/8/15 | 6.74 | 5 | 1
PABL037 | 2011/8/23 | 7.07 | 5 | 3
PABL038 | 2011/8/15 | 6.73 | 5 | 0
PABL038 | 2011/10/3 | 7.39 | 5 | 2
PABL038 | 2017/12/4 | 7.41 | 4 | 4
PABL038 | 2017/12/4 | 7.91 | 5 | 5
PABL038 | 2012/2/27 | 7.95 | 5 | 5
PABL040 | 2011/8/23 | 7.08 | 5 | 0
PABL040 | 2011/8/15 | 7.31 | 5 | 5
PABL041 | 2010/9/21 | 6.66 | 5 | 3
PABL041 | 2010/2/26 | 7.04 | 5 | 5
PABL042 | 2010/11/2 | 7.06 | 5 | 0
PABL042 | 2010/2/26 | 7.26 | 5 | 1
PABL042 | 2012/2/27 | 7.88 | 5 | 5
PABL043 | 2010/2/26 | 6.91 | 5 | 0
PABL043 | 2010/9/28 | 7.09 | 5 | 0
PABL043 | 2012/2/27 | 7.79 | 5 | 0
PABL043 | 2012/5/23 | 8.42 | 5 | 5
PABL044 | 2011/10/3 | 6.93 | 5 | 0
PABL044 | 2011/10/24 | 7.47 | 5 | 5
PABL046 | 2011/8/29 | 6.60 | 5 | 0
PABL046 | 2011/10/10 | 7.43 | 5 | 5
PABL047 | 2010/2/26 | 6.82 | 5 | 0
PABL047 | 2010/9/27 | 7.27 | 5 | 5
PABL048 | 2010/3/4 | 6.64 | 5 | 0
PABL048 | 2010/9/21 | 7.46 | 5 | 5
PABL049 | 2018/2/13 | 5.94 | 5 | 0
PABL049 | 2017/11/5 | 6.40 | 5 | 5
PABL049 | 2017/12/18 | 6.43 | 5 | 5
PABL049 | 2013/6/13 | 6.44 | 5 | 4
PABL049 | 2017/11/14 | 6.50 | 5 | 5
PABL049 | 2013/3/5 | 6.60 | 5 | 5
PABL049 | 2010/8/30 | 6.73 | 5 | 4
PABL049 | 2010/11/1 | 6.91 | 5 | 4
PABL049 | 2013/2/12 | 6.91 | 5 | 5
PABL049 | 2013/3/5 | 6.92 | 5 | 5
PABL049 | 2010/3/4 | 7.09 | 5 | 4
PABL051 | 2011/8/29 | 6.62 | 5 | 0
PABL051 | 2011/10/10 | 7.33 | 5 | 0
PABL051 | 2012/2/21 | 7.65 | 5 | 5
PABL052 | 2011/9/13 | 6.67 | 5 | 0
PABL052 | 2011/9/19 | 7.30 | 5 | 1
PABL052 | 2012/2/27 | 7.79 | 5 | 2
PABL052 | 2012/5/23 | 8.06 | 5 | 5
PABL053 | 2011/8/29 | 6.41 | 5 | 0
PABL053 | 2011/9/13 | 6.79 | 5 | 0
PABL053 | 2011/9/19 | 7.21 | 5 | 5
PABL054 | 2017/11/28 | 6.30 | 5 | 0
PABL054 | 2017/11/14 | 6.45 | 5 | 0
PABL054 | 2011/8/29 | 6.71 | 5 | 0
PABL054 | 2017/11/28 | 6.84 | 5 | 3
PABL054 | 2017/11/14 | 7.16 | 5 | 5
PABL054 | 2011/9/19 | 7.42 | 5 | 4
PABL055 | 2011/8/29 | 6.44 | 5 | 0
PABL055 | 2011/10/3 | 6.83 | 5 | 1
PABL055 | 2011/9/13 | 7.04 | 5 | 3
PABL055 | 2011/9/19 | 7.27 | 5 | 5
PABL056 | 2010/3/4 | 6.85 | 5 | 0
PABL056 | 2010/9/27 | 7.39 | 5 | 0
PABL056 | 2012/4/17 | 7.95 | 5 | 5
PABL056 | 2012/4/10 | 8.17 | 5 | 5
PABL056 | 2012/2/27 | 8.19 | 5 | 5
PABL057 | 2011/8/29 | 6.56 | 5 | 0
PABL057 | 2011/9/13 | 7.30 | 5 | 4
PABL057 | 2011/9/19 | 7.46 | 5 | 5
PABL058 | 2011/9/13 | 6.91 | 5 | 0
PABL058 | 2011/9/19 | 7.57 | 5 | 1
PABL058 | 2012/4/10 | 7.86 | 5 | 5
PABL059 | 2010/3/4 | 6.81 | 5 | 0
PABL059 | 2010/9/27 | 7.29 | 5 | 1
PABL059 | 2012/4/17 | 7.80 | 5 | 5
PABL059 | 2012/3/20 | 8.11 | 5 | 5
PABL059 | 2012/4/10 | 8.17 | 5 | 5
PABL060 | 2010/8/30 | 6.46 | 5 | 0
PABL060 | 2010/3/4 | 7.13 | 5 | 5
PABL061 | 2010/9/13 | 6.43 | 5 | 2
PABL061 | 2010/3/4 | 7.24 | 5 | 5
PABL062 | 2011/9/13 | 6.94 | 5 | 0
PABL062 | 2011/9/19 | 7.46 | 5 | 1
PABL062 | 2012/3/20 | 7.98 | 5 | 5
PABL063 | 2010/3/11 | 6.08 | 5 | 0
PABL063 | 2010/11/1 | 6.46 | 5 | 0
PABL063 | 2010/9/14 | 7.31 | 5 | 4
PABL064 | 2011/9/13 | 6.74 | 5 | 0
PABL064 | 2011/9/19 | 7.31 | 5 | 0
PABL064 | 2012/3/20 | 7.54 | 5 | 5
PABL065 | 2011/9/19 | 7.24 | 5 | 0
PABL065 | 2012/4/24 | 7.66 | 5 | 0
PABL065 | 2012/4/3 | 8.17 | 5 | 5
PABL066 | 2011/9/13 | 6.96 | 5 | 0
PABL066 | 2011/10/10 | 7.53 | 5 | 0
PABL066 | 2012/3/20 | 7.81 | 5 | 5
PABL067 | 2011/10/3 | 6.78 | 5 | 1
PABL067 | 2011/10/10 | 7.42 | 5 | 1
PABL067 | 2012/2/14 | 7.67 | 5 | 5
PABL068 | 2010/9/13 | 6.54 | 5 | 3
PABL068 | 2017/12/11 | 6.60 | 5 | 5
PABL068 | 2017/12/4 | 6.70 | 5 | 5
PABL068 | 2017/12/4 | 7.00 | 5 | 5
PABL068 | 2010/3/11 | 7.17 | 5 | 5
PABL069 | 2011/9/19 | 7.00 | 5 | 2
PABL069 | 2011/10/3 | 7.37 | 5 | 5
PABL070 | 2010/9/13 | 6.37 | 5 | 0
PABL070 | 2010/3/11 | 6.54 | 5 | 4
PABL070 | 2017/12/18 | 6.70 | 5 | 5
PABL070 | 2017/12/4 | 6.76 | 5 | 5
PABL070 | 2017/12/4 | 7.06 | 5 | 5
PABL070 | 2017/12/18 | 7.31 | 5 | 5
PABL071 | 2011/10/10 | 7.13 | 5 | 0
PABL071 | 2011/10/17 | 7.19 | 5 | 2
PABL071 | 2011/10/3 | 7.41 | 5 | 4
PABL071 | 2012/3/27 | 7.66 | 5 | 5
PABL072 | 2010/9/27 | 6.29 | 5 | 0
PABL072 | 2010/11/1 | 6.31 | 5 | 0
PABL072 | 2018/2/6 | 6.74 | 5 | 4
PABL073 | 2011/10/10 | 6.86 | 5 | 2
PABL073 | 2011/10/25 | 7.24 | 5 | 5
PABL074 | 2010/3/11 | 6.51 | 5 | 0
PABL074 | 2010/9/21 | 7.23 | 5 | 1
PABL074 | 2012/3/27 | 7.76 | 5 | 5
PABL075 | 2011/10/17 | 6.92 | 5 | 2
PABL075 | 2011/10/10 | 7.42 | 5 | 5
PABL076 | 2011/10/17 | 6.90 | 5 | 1
PABL076 | 2011/10/24 | 7.30 | 5 | 5
PABL077 | 2011/10/17 | 6.64 | 5 | 1
PABL077 | 2011/10/24 | 7.27 | 5 | 5
PABL078 |   | 6.23 | 5 | 0
PABL078 | 2011/10/31 | 6.23 | 5 | 0
PABL078 | 2011/10/25 | 6.83 | 5 | 4
PABL079 | 2011/10/25 | 6.55 | 5 | 2
PABL079 | 2011/10/31 | 7.02 | 5 | 5
PABL080 | 2010/9/13 | 6.56 | 5 | 0
PABL080 | 2010/3/11 | 7.14 | 5 | 3
PABL081 | 2011/10/17 | 7.02 | 5 | 0
PABL081 | 2011/10/24 | 7.44 | 5 | 0
PABL081 | 2012/4/24 | 7.60 | 5 | 4
PABL081 | 2012/2/21 | 8.09 | 5 | 5
PABL081 | 2012/4/10 | 8.13 | 5 | 5
PABL082 | 2011/10/25 | 6.84 | 5 | 0
PABL082 | 2011/10/31 | 7.31 | 5 | 0
PABL082 | 2017/12/11 | 7.70 | 4 | 4
PABL082 | 2012/3/27 | 7.96 | 5 | 2
PABL082 | 2012/2/21 | 7.99 | 5 | 1
PABL082 | 2017/12/11 | 8.17 | 5 | 5
PABL082 | 2012/6/4 | 8.54 | 5 | 5
PABL083 | 2011/11/28 | 5.88 | 5 | 0
PABL083 | 2011/12/12 | 5.96 | 5 | 0
PABL083 | 2011/10/31 | 6.00 | 5 | 0
PABL083 | 2011/12/5 | 6.04 | 5 | 0
PABL083 | 2018/1/15 | 6.40 | 5 | 3
PABL083 | 2017/11/7 | 6.45 | 5 | 3
PABL083 | 2018/1/15 | 6.80 | 5 | 5
PABL083 | 2011/10/24 | 6.82 | 5 | 4
PABL083 | 2013/7/15 | 7.24 | 5 | 5
PABL083 | 2011/10/17 | 7.36 | 5 | 5
PABL084 | 2011/10/25 | 6.42 | 5 | 0
PABL084 | 2011/10/31 | 6.76 | 5 | 5
PABL085 | 2011/10/31 | 6.22 | 5 | 0
PABL085 | 2011/10/25 | 6.72 | 5 | 3
PABL086 | 2010/3/11 | 7.02 | 5 | 0
PABL086 | 2010/11/2 | 7.29 | 5 | 5
PABL088 | 2011/10/25 | 6.64 | 5 | 0
PABL088 | 2011/10/31 | 7.23 | 5 | 0
PABL088 | 2012/2/21 | 7.62 | 5 | 5
PABL089 | 2010/3/15 | 7.04 | 5 | 0
PABL089 | 2010/11/2 | 7.31 | 5 | 2
PABL089 | 2012/3/27 | 7.96 | 5 | 5
PABL090 | 2011/11/7 | 6.45 | 5 | 1
PABL090 | 2011/10/31 | 6.74 | 5 | 3
PABL091 | 2011/10/31 | 7.10 | 5 | 1
PABL091 | 2011/11/7 | 7.63 | 5 | 5
PABL092 | 2011/10/31 | 6.65 | 5 | 0
PABL092 | 2011/11/7 | 6.98 | 5 | 0
PABL092 | 2011/11/14 | 6.98 | 5 | 1
PABL092 | 2011/11/28 | 7.13 | 5 | 1
PABL092 | 2011/12/5 | 7.36 | 5 | 3
PABL092 | 2012/3/27 | 7.84 | 5 | 1
PABL092 | 2012/5/23 | 8.21 | 5 | 5
PABL093 | 2010/2/8 | 6.44 | 5 | 4
PABL093 | 2011/10/10 | 7.40 | 5 | 5
PABL093 | 2012/2/21 | 7.79 | 5 | 5
PABL094 | 2010/3/15 | 6.16 | 5 | 0
PABL094 | 2010/11/1 | 6.29 | 5 | 0
PABL094 | 2010/9/14 | 7.14 | 5 | 3
PABL095 | 2011/11/7 | 6.48 | 5 | 0
PABL095 | 2011/10/31 | 6.89 | 5 | 5
PABL096 | 2011/11/28 | 6.46 | 5 | 2
PABL096 | 2011/11/14 | 6.89 | 4 | 3
PABL096 | 2011/11/7 | 6.96 | 5 | 5
PABL097 | 2010/3/15 | 6.11 | 5 | 0
PABL097 | 2010/9/27 | 6.48 | 5 | 0
PABL097 | 2017/12/4 | 6.48 | 5 | 5
PABL097 | 2010/9/21 | 7.21 | 5 | 5
PABL097 | 2017/12/4 | 7.23 | 5 | 3
PABL098 | 2011/11/7 | 6.45 | 5 | 0
PABL098 | 2011/12/5 | 6.89 | 5 | 1
PABL098 | 2011/11/14 | 7.12 | 5 | 4
PABL100 | 2011/11/7 | 6.82 | 5 | 1
PABL100 | 2011/11/14 | 7.31 | 5 | 5
PABL101 | 2011/11/7 | 6.82 | 5 | 1
PABL101 | 2011/11/16 | 7.35 | 5 | 5
PABL102 | 2011/11/16 | 6.18 | 5 | 1
PABL102 | 2011/11/7 | 6.96 | 5 | 5
PABL103 | 2011/8/23 | 6.47 | 5 | 0
PABL103 | 2011/8/29 | 7.13 | 5 | 0
PABL103 | 2012/3/27 | 7.70 | 5 | 0
PABL103 | 2012/5/23 | 8.17 | 5 | 3
PABL104 | 2011/11/7 | 6.58 | 5 | 0
PABL104 | 2011/11/16 | 7.48 | 5 | 0
PABL104 | 2012/3/27 | 7.61 | 5 | 1
PABL104 | 2012/5/23 | 8.18 | 5 | 4
PABL105 | 2011/11/7 | 6.79 | 5 | 0
PABL105 | 2011/11/28 | 7.33 | 5 | 1
PABL105 | 2012/4/10 | 7.89 | 5 | 3
PABL105 | 2012/4/3 | 8.04 | 5 | 5
PABL106 | 2011/8/23 | 6.48 | 5 | 3
PABL106 | 2011/12/5 | 7.41 | 5 | 5
PABL107 | 2011/11/28 | 6.10 | 5 | 0
PABL107 | 2011/12/5 | 6.31 | 5 | 2
PABL107 | 2018/1/15 | 6.40 | 5 | 3
PABL107 | 2017/10/23 | 6.53 | 5 | 5
PABL107 | 2011/11/7 | 6.62 | 5 | 5
PABL107 | 2013/9/24 | 6.64 | 5 | 5
PABL107 | 2018/1/15 | 6.70 | 5 | 5
PABL108 | 2010/3/18 | 6.45 | 5 | 1
PABL108 | 2010/9/21 | 6.94 | 5 | 3
PAC1 | 2013/4/23 | 5.88 | 3 | 0
PAC1 | 2013/4/11 | 5.92 | 3 | 0
PAC1 | 2013/4/16 | 6.00 | 3 | 0
PAC1 | 2011/11/16 | 6.16 | 5 | 2
PAC1 | 2013/4/16 | 6.44 | 3 | 0
PAC1 | 2013/4/11 | 6.45 | 3 | 3
PAC1 | 2011/11/14 | 6.60 | 5 | 5
PAC1 | 2013/4/23 | 6.82 | 3 | 3
PAC6 | 2013/4/16 | 6.00 | 3 | 1
PAC6 | 2013/4/11 | 6.04 | 3 | 0
PAC6 | 2013/4/11 | 6.35 | 3 | 3
PAC6 | 2011/11/16 | 6.37 | 5 | 5
PAC6 | 2013/4/16 | 6.40 | 3 | 3
PAC6 | 2011/11/14 | 6.79 | 5 | 5
S10 | 2014/1/28 | 5.82 | 5 | 1
S10 | 2014/1/22 | 6.22 | 5 | 5
S10 | 2013/12/4 | 6.45 | 5 | 4
S10 | 2014/1/15 | 6.68 | 5 | 5
S11 | 2014/2/11 | 5.56 | 5 | 1
S11 | 2014/2/11 | 5.88 | 5 | 0
S11 | 2014/2/4 | 6.28 | 5 | 5
S11 | 2013/12/4 | 6.31 | 5 | 1
S11 | 2014/1/28 | 6.63 | 5 | 5
S11 | 2014/1/15 | 6.68 | 5 | 5
S11 | 2014/1/22 | 6.73 | 5 | 4
S12 | 2014/1/22 | 6.07 | 5 | 0
S12 | 2014/1/15 | 6.21 | 5 | 1
S12 | 2014/1/28 | 6.67 | 5 | 3
S12 | 2013/12/4 | 6.78 | 5 | 5
S13 | 2014/2/4 | 6.15 | 5 | 0
S13 | 2014/1/28 | 6.40 | 5 | 5
S13 | 2014/1/15 | 6.96 | 5 | 5
S13 | 2014/1/22 | 7.03 | 5 | 5
S14 | 2014/1/15 | 6.58 | 5 | 0
S14 | 2014/1/22 | 7.05 | 5 | 5
S15 | 2014/1/28 | 5.94 | 5 | 0
S15 | 2014/2/4 | 6.25 | 5 | 0
S15 | 2014/1/15 | 6.48 | 5 | 5
S16 | 2014/1/15 | 6.61 | 5 | 0
S16 | 2014/1/22 | 7.15 | 4 | 1
S16 | 2014/1/28 | 7.42 | 5 | 5
S17 | 2014/1/15 | 6.45 | 5 | 0
S17 | 2014/1/22 | 6.74 | 5 | 2
S17 | 2014/1/28 | 6.98 | 5 | 4
S2 | 2014/1/21 | 5.88 | 5 | 0
S2 | 2014/2/4 | 6.26 | 5 | 0
S2 | 2014/1/14 | 6.34 | 5 | 4
S2 | 2018/2/6 | 6.82 | 5 | 5
S3 | 2014/2/4 | 5.92 | 5 | 2
S3 | 2014/1/21 | 6.25 | 5 | 3
S3 | 2014/1/14 | 6.57 | 5 | 5
S4 | 2014/2/11 | 6.01 | 5 | 2
S4 | 2014/2/4 | 6.21 | 5 | 5
S4 | 2014/2/11 | 6.23 | 5 | 5
S4 | 2014/1/28 | 6.52 | 5 | 5
S4 | 2013/11/19 | 6.55 | 5 | 5
S4 | 2014/1/14 | 7.04 | 5 | 5
S4 | 2014/1/21 | 7.14 | 5 | 5
S5 | 2014/2/4 | 5.90 | 5 | 1
S5 | 2014/1/28 | 6.03 | 5 | 4
S5 | 2013/12/4 | 6.15 | 5 | 5
S5 | 2014/1/21 | 6.28 | 5 | 3
S5 | 2014/1/14 | 6.59 | 5 | 5
S7 | 2014/1/28 | 6.20 | 5 | 1
S7 | 2013/12/4 | 6.26 | 5 | 3
S7 | 2014/1/21 | 6.63 | 5 | 3
S7 | 2014/1/14 | 6.71 | 5 | 5
S8 | 2014/2/4 | 5.73 | 5 | 1
S8 | 2013/12/4 | 5.92 | 5 | 2
S8 | 2014/1/28 | 6.00 | 5 | 1
S8 | 2014/1/21 | 6.63 | 5 | 4
S8 | 2014/1/14 | 6.79 | 5 | 5
S9 | 2013/12/4 | 6.36 | 5 | 1
S9 | 2014/1/21 | 6.49 | 5 | 1
S9 | 2014/1/14 | 6.76 | 5 | 3
PASP048 | 2018/1/8 | 6.29 | 5 | 1
PASP048 | 2017/7/11 | 6.82 | 5 | 4
PASP048 | 2017/7/11 | 7.27 | 5 | 5
PASP048 | 2017/7/11 | 7.96 | 5 | 5
PASP146 | 2018/1/22 | 6.24 | 5 | 0
PASP146 | 2017/10/30 | 6.57 | 4 | 4
PASP146 | 2017/10/30 | 7.05 | 5 | 5
PASP146 | 2017/10/30 | 7.59 | 5 | 5
PASP170 | 2017/10/31 | 6.67 | 5 | 0
PASP170 | 2017/10/31 | 7.12 | 5 | 1
PASP170 | 2017/10/31 | 7.67 | 5 | 4
PASP198 | 2017/11/6 | 6.40 | 5 | 1
PASP198 | 2017/11/6 | 6.98 | 5 | 5
PASP198 | 2017/11/6 | 7.47 | 5 | 5
PASP204 | 2018/3/13 | 5.81 | 4 | 0
PASP204 | 2018/3/13 | 6.03 | 5 | 0
PASP204 | 2018/1/30 | 6.61 | 4 | 4
PASP204 | 2017/11/13 | 6.69 | 5 | 5
PASP204 | 2017/11/13 | 7.22 | 5 | 5
PASP204 | 2017/11/13 | 7.66 | 4 | 4
PASP208 | 2018/3/13 | 6.12 | 5 | 0
PASP208 | 2017/11/14 | 6.46 | 4 | 4
PASP208 | 2017/11/28 | 6.51 | 5 | 5
PASP208 | 2017/11/14 | 7.07 | 4 | 4
PASP208 | 2017/11/14 | 7.46 | 5 | 5
PASP251 | 2017/12/18 | 6.34 | 5 | 3
PASP251 | 2017/12/18 | 6.93 | 5 | 5
PASP251 | 2017/12/18 | 7.60 | 5 | 5
PASP269 | 2018/1/8 | 6.39 | 4 | 2
PASP269 | 2018/1/8 | 6.88 | 5 | 5
PASP269 | 2018/1/8 | 7.43 | 4 | 4
PASP309 | 2018/2/6 | 6.66 | 5 | 2
PASP309 | 2018/2/6 | 7.19 | 5 | 5
PASP309 | 2018/1/30 | 7.67 | 5 | 5
PASP315 | 2017/9/12 | 6.24 | 5 | 0
PASP315 | 2017/9/12 | 6.76 | 5 | 5
PASP315 | 2017/9/12 | 7.12 | 3 | 3
PASP352 | 2018/1/30 | 6.59 | 4 | 1
PASP352 | 2018/1/30 | 7.10 | 5 | 5
PASP352 | 2018/1/30 | 7.53 | 5 | 5
PASP388 | 2017/8/7 | 6.50 | 5 | 0
PASP388 | 2017/8/7 | 6.98 | 5 | 0
PASP388 | 2017/8/7 | 7.49 | 5 | 5
PASP398 | 2017/8/14 | 6.93 | 5 | 0
PASP398 | 2017/8/14 | 7.30 | 5 | 2
PASP398 | 2017/8/14 | 7.82 | 5 | 5
PASP415 | 2018/2/26 | 6.09 | 5 | 0
PASP415 | 2018/2/5 | 6.22 | 5 | 0
PASP415 | 2018/2/5 | 6.85 | 5 | 4
PASP415 | 2018/2/5 | 7.41 | 4 | 4
PASP450 | 2018/2/13 | 6.52 | 5 | 0
PASP450 | 2018/2/13 | 6.83 | 5 | 0
PASP450 | 2018/2/13 | 7.24 | 5 | 1
PASP450 | 2018/2/26 | 8.05 | 5 | 3
PASP453 | 2017/9/11 | 6.30 | 5 | 3
PASP453 | 2017/9/11 | 6.92 | 5 | 5
PASP453 | 2017/9/11 | 7.29 | 5 | 5
PASP471 | 2018/3/13 | 5.89 | 5 | 0
PASP471 | 2018/3/13 | 6.09 | 5 | 0
PASP471 | 2017/9/4 | 6.54 | 5 | 5
PASP471 | 2017/9/4 | 7.09 | 5 | 5
PASP471 | 2017/9/4 | 7.52 | 5 | 5
PASP475 | 2018/2/26 | 6.28 | 5 | 1
PASP475 | 2018/2/26 | 6.66 | 5 | 5
PASP475 | 2018/2/26 | 7.35 | 5 | 5
PASP496 | 2017/10/16 | 6.70 | 5 | 0
PASP496 | 2017/10/16 | 7.18 | 5 | 0
PASP496 | 2017/10/16 | 7.70 | 5 | 5
PASP499 | 2017/10/17 | 6.24 | 5 | 0
PASP499 | 2017/10/17 | 6.78 | 5 | 0
PASP499 | 2017/10/17 | 7.35 | 5 | 2
PASP499 | 2018/1/15 | 7.42 | 5 | 5
PASP518 | 2018/2/26 | 6.12 | 5 | 0
PASP518 | 2018/2/26 | 6.63 | 4 | 1
PASP518 | 2018/2/26 | 7.19 | 5 | 3
PASP527 | 2017/5/15 | 6.16 | 5 | 0
PASP527 | 2017/5/30 | 6.28 | 5 | 1
PASP527 | 2017/5/30 | 6.95 | 5 | 5
PASP527 | 2017/5/15 | 7.15 | 5 | 5
PASP612 | 2018/1/23 | 6.56 | 4 | 0
PASP612 | 2018/1/23 | 7.13 | 5 | 3
PASP612 | 2018/1/23 | 7.63 | 5 | 5
PASP639 | 2018/1/22 | 6.66 | 4 | 0
PASP639 | 2018/1/22 | 7.16 | 5 | 1
PASP639 | 2018/1/22 | 7.61 | 5 | 4
PASP657 | 2018/1/15 | 6.63 | 5 | 0
PASP657 | 2018/1/15 | 7.20 | 5 | 0
PASP657 | 2018/1/15 | 7.81 | 5 | 2
PASP657 | 2018/1/23 | 8.12 | 5 | 5

**Comment by daniel-gerhard** [comment]
Hi,
You are trying to fit a two-parameter model for each of the 140 levels in type. Some type levels only contain two observations, which is enough to obtain point estimates, but you will not be able to estimate standard error for the parameters.
You might want to reduce the number of parameters in the model - estimate a joint steepness parameter b for all the types and only separate ED50 parameters for each of the types using the pmodels argument.
Ngā mihi,
Daniel
