### ISSUE TITLE
reset options(warn) in drm() on exit

### ISSUE THREAD

**Issue by BastiHz** [DoseResponse/drc#9]
I like to use `options(warn=1)` in my scripts. But after calling `drm()` the value is set to 0. That's because `drm()` modifies it and this change persists after the function exits. It is not very nice to mess with the users options. Please cache them and reset them with `on.exit`, thank you.

Example:
```
library(drc)
options(warn = 1)
getOption("warn")  # prints 1
drm(c(9, 8, 2, 1) ~ c(1, 2, 3, 4), fct = W1.3())
getOption("warn")  # prints 0
```

**Comment by daniel-gerhard** [comment]
all options() calls should now reset on.exit.
Thanks!

**Comment by BastiHz** [comment]
Wow, that was fast. Thank you.
